name: Lint Python Code
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.1333
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: 'pip'
      - name: Install dependencies
        run: 
          python -m pip install --upgrade pip
          python -m pip install ruff
      - name: Lint with ruff
        run:  ruff check --output-format=github
